# Generated by Django 3.2.5 on 2023-07-01 05:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_user_role'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='merchant',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='customer.profile'),
            preserve_default=False,
        ),
    ]
