# Generated by Django 3.2.5 on 2023-03-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(blank=True, choices=[(2, 'Merchant'), (1, 'Customer')], null=True),
        ),
    ]
