# Generated by Django 3.2.5 on 2023-07-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
        ('customer', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(blank=True, choices=[(2, 'Merchant'), (1, 'Customer')], null=True),
        ),
    ]
